import json

CUBIC_METERS_TO_GALLONS = 264.172052

# Simplified runoff coefficient assumptions.
PRE_DEVELOPMENT_COEFFICIENT = 0.20
ROOF_COEFFICIENT = 0.95

with open(
    "impervious_metrics.json",
    "r",
    encoding="utf-8"
) as file:
    impervious_metrics = json.load(file)

roof_area_m2 = impervious_metrics["roof_area_m2"]

storm_scenarios = {}

for rainfall_inches in [1, 2, 3]:
    rainfall_meters = rainfall_inches * 0.0254

    total_rainfall_m3 = (
        roof_area_m2 * rainfall_meters
    )

    pre_development_runoff_m3 = (
        total_rainfall_m3
        * PRE_DEVELOPMENT_COEFFICIENT
    )

    post_development_runoff_m3 = (
        total_rainfall_m3
        * ROOF_COEFFICIENT
    )

    additional_runoff_m3 = (
        post_development_runoff_m3
        - pre_development_runoff_m3
    )

    additional_runoff_gallons = (
        additional_runoff_m3
        * CUBIC_METERS_TO_GALLONS
    )

    storm_scenarios[f"{rainfall_inches}_inch_storm"] = {
        "rainfall_inches": rainfall_inches,
        "total_rainfall_on_roof_m3": round(
            total_rainfall_m3,
            2
        ),
        "estimated_pre_development_runoff_m3": round(
            pre_development_runoff_m3,
            2
        ),
        "estimated_post_development_runoff_m3": round(
            post_development_runoff_m3,
            2
        ),
        "additional_runoff_m3": round(
            additional_runoff_m3,
            2
        ),
        "additional_runoff_gallons": round(
            additional_runoff_gallons
        )
    }

results = {
    "site": "Amazon Distribution Center - Clear Brook",
    "impervious_area_method": (
        "Largest mapped building footprint only"
    ),
    "roof_area_m2": roof_area_m2,
    "roof_area_acres": impervious_metrics[
        "roof_area_acres"
    ],
    "pre_development_runoff_coefficient": (
        PRE_DEVELOPMENT_COEFFICIENT
    ),
    "roof_runoff_coefficient": ROOF_COEFFICIENT,
    "storm_scenarios": storm_scenarios,
    "interpretation": (
        "Estimated additional runoff generated by replacing "
        "previous land cover with the warehouse roof."
    ),
    "limitations": [
        "Uses simplified runoff coefficients.",
        "Excludes parking lots, loading areas, and roads.",
        "Does not account for detention ponds or drainage infrastructure.",
        "Intended as a screening estimate, not an engineering design calculation."
    ]
}

with open(
    "runoff_debt.json",
    "w",
    encoding="utf-8"
) as file:
    json.dump(results, file, indent=2)

print(json.dumps(results, indent=2))
