import puppeteer from "puppeteer-core";
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
const b=await puppeteer.launch({executablePath:'/usr/local/bin/google-chrome',headless:'new',args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage(); await p.setViewport({width:1200,height:800});
p.on('console',m=>{if(m.type()==='error')console.log('[err]',m.text().slice(0,200))});
const tiles=[];
p.on('response',r=>{const u=r.url(); if(u.includes('wayback.maptiles')) tiles.push(r.status()+' '+u.split('/MapServer/tile/')[1]);});
await p.goto('http://127.0.0.1:4317',{waitUntil:'networkidle2'});
await sleep(4000);
await p.type('input[role="combobox"]','Clear Brook, Virginia',{delay:25});
await p.waitForSelector('ul li button'); await p.click('ul li button');
await p.waitForFunction(()=>/Runoff Pressure|channel/i.test(document.body.innerText),{timeout:45000}).catch(()=>{});
await sleep(11000);
const clickTitle=(t)=>p.evaluate((name)=>{[...document.querySelectorAll('button')].find(n=>n.getAttribute('title')===name)?.click();},t);
await clickTitle('Imagery'); await sleep(1500);
const clickYear=(y)=>p.evaluate((v)=>{const n=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===v); n?.click(); return !!n;},y);
console.log('2014 clicked', await clickYear('2014')); await sleep(9000);
await p.screenshot({path:'/tmp/smoke/e2014.png'});
console.log('tiles after 2014:', tiles.length, tiles.slice(-3));
console.log('2024 clicked', await clickYear('2024')); await sleep(9000);
await p.screenshot({path:'/tmp/smoke/e2024.png'});
console.log('tiles after 2024:', tiles.length, tiles.slice(-3));
const state=await p.evaluate(()=>{const m=window.__hydroMap;const s=m.getSource('imagery-historic');return{tiles:s.tiles,vis:m.getLayoutProperty('imagery-historic','visibility'),op:m.getPaintProperty('imagery-historic','raster-opacity')};});
console.log(JSON.stringify(state));
await b.close();
